### ISSUE TITLE
Ideas 4 u :blobheart:

### ISSUE THREAD

**Issue by brandonskerritt** [0xkurome/Kurcoder#1]
Hi Kurome!!!

Here's some wittle ideas 4 u :3 

https://cjolowicz.github.io/posts/hypermodern-python-01-setup/
^^ great series of blog posts of updating your project to be "modern", I followed this for Ciphey and I loved it!

https://github.com/faressoft/terminalizer
^^ what i use for gifs

https://shields.io/
^^ what i use for cool github readme badges

try to implement some basic CI / testing using PyTest, your programs functions will need to return the value instead of calling `main()` though

You should implement modules, so instead of it all being in one file you can just import each file and work on it that way.

This will simplify your codebase a lot in the long run, will allow you to see bugs easier and compartmentalise your code.

Seperate your code into a `src/` folder so the root directory of the repo will be clean

**Comment by 0xkurome** [comment]
thanks for the suggestions.
